# Generated by Django 2.2 on 2021-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=20, unique=True)),
                ('isi', models.TextField(max_length=300)),
                ('penulis', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
