# Generated by Django 2.2 on 2021-01-14 16:38

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(max_length=30, validators=[blog.validators.validatePenulis]),
        ),
    ]
