# Generated by Django 2.2 on 2021-01-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210117_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='photo',
            field=models.FileField(upload_to='media'),
        ),
    ]
