# Generated by Django 2.2 on 2021-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210117_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
