# Generated by Django 2.2 on 2021-01-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
